---
plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-factory_bot

inherit_from:
  - .rubocop/rails.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.4
  Exclude:
    - bin/*
    - config/**/*
    - spec/rails_helper.rb
    - test/**/*
    - db/**/*

Metrics/ClassLength:
  CountAsOne:
    - array
    - heredoc
    - method_call
    - hash

Metrics/ModuleLength:
  CountAsOne:
    - array
    - heredoc
    - method_call
    - hash

Metrics/BlockLength:
  Exclude:
    - Guardfile
    - Gemfile
    - db/migrate/*.rb
  CountAsOne:
    - array
    - heredoc
    - method_call
    - hash

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb
  CountAsOne:
    - array
    - heredoc
    - method_call
    - hash

Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required

Style/WordArray:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Exclude:
    - app/models/**/*.rb

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Layout/LineLength:
  Max: 100

Layout/TrailingEmptyLines:
  Enabled: true
  EnforcedStyle: final_newline

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Style/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: false

Style/HashLikeCase:
  Enabled: true

Style/HashSyntax:
  EnforcedShorthandSyntax: either_consistent

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/NumericLiterals:
  Enabled: false

Style/CharacterLiteral:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

Lint/ItWithoutArgumentsInBlock:
  Enabled: false
