apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-migrations-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-upgrade,post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrations
          {{- include "base-container" . | nindent 10 }}
          command: ["sh", "-c", "bin/rails db:prepare"]
          ports: []
      volumes:
        - name: sqlite-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-sqlite-pvc
