apiVersion: v1
kind: Secret
metadata:
  name: sroodle-secrets
  labels:
    {{- include "sroodle.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
type: Opaque
data:
  rails-master-key: {{ .Values.railsMasterKey | b64enc | quote }}
