apiVersion: v1
kind: Secret
metadata:
  name: sroodle-secrets
  labels:
    {{- include "sroodle.labels" . | nindent 4 }}
type: Opaque
data:
  rails-master-key: {{ .Values.railsMasterKey | b64enc | quote }}
